# coding: utf-8

"""
    fl-api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2022-06-24T11:05:34Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_organizations_get(self):
        """Test case for organizations_get

        """
        print("Test")
        response = self.api.organizations_get(async_req=False, _preload_content=False)
        print(response.data)


    def organizations_get_with_http_info(self):
        """Test case for organizations_org_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
